openapi: 3.0.0
info:
  title: ATM Locator API
  version: 1.0.0
paths:
  /atms:
    get:
      description: >-
        Retrieve a list of ATMs based on specified criteria (e.g., location,
        radius, features).
      operationId: getAtms
      parameters:
        - description: Latitude of the location to search near.
          in: query
          name: latitude
          schema:
            format: float
            type: number
        - description: Longitude of the location to search near.
          in: query
          name: longitude
          schema:
            format: float
            type: number
        - description: Radius in meters to search within.
          in: query
          name: radius
          schema:
            format: int32
            type: integer
        - description: Comma-separated list of features the ATM should support.
          in: query
          name: features
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ATM"
                type: array
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error
      summary: Retrieve a list of ATMs
      tags:
        - atms
    post:
      description: Creates a new ATM entry. Requires administrative privileges.
      operationId: createAtm
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ATM"
        description: ATM object to be created
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ATM"
          description: ATM created successfully
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Forbidden - insufficient privileges
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal server error
      summary: Create a new ATM entry
      tags:
        - atms
  /atms/{atmId}:
    delete:
      description: Delete a specific ATM entry. Requires administrative privileges.
      operationId: deleteAtm
      parameters:
        - description: ID of the ATM to delete
          in: path
          name: atmId
          required: true
          schema:
            type: string
      responses:
        "204":
          description: ATM deleted successfully
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Unauthorized - Requires administrative privileges
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: ATM not found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal server error
      summary: Delete an ATM
      tags:
        - atms
    get:
      description: Retrieve detailed information about a specific ATM using its unique ID.
      operationId: getAtmById
      parameters:
        - description: Unique identifier for the ATM.
          in: path
          name: atmId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ATM"
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Invalid ATM ID supplied
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: ATM not found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal server error
      summary: Retrieve ATM by ID
      tags:
        - atms
    parameters:
      - in: path
        name: atmId
        required: true
        schema:
          type: string
    put:
      description: >-
        Update the information of a specific ATM. Requires administrative
        privileges.
      operationId: updateAtm
      parameters:
        - description: ID of the ATM to update
          in: path
          name: atmId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ATM"
        description: ATM object to update
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ATM"
          description: Successful update
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad request
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: ATM not found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal server error
      summary: Update an ATM
      tags:
        - atms
  /atms/{atmId}/report:
    parameters:
      - in: path
        name: atmId
        required: true
        schema:
          type: string
    post:
      description: Report an issue related to a specific ATM using its ID.
      operationId: reportAtmIssue
      parameters:
        - description: ID of the ATM to report
          in: path
          name: atmId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  description: Description of the issue reported.
                  type: string
                reporter:
                  description: Information about the reporter (e.g., user ID).
                  type: string
              required:
                - description
              type: object
        description: Report details
      responses:
        "201":
          content:
            application/json:
              schema:
                properties:
                  reportDate:
                    description: Date and time the report was submitted.
                    format: date-time
                    type: string
                  reportId:
                    description: Unique identifier for the report.
                    type: string
                  status:
                    description: Status of the report (e.g., open, in progress, resolved).
                    type: string
                type: object
          description: Report submitted successfully
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: ATM not found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error
      summary: Report an issue with a specific ATM
      tags:
        - atms
  /atms/nearby:
    get:
      description: Retrieves a list of ATMs located near the provided address.
      operationId: getNearbyAtms
      parameters:
        - description: The address to search near.
          in: query
          name: address
          required: true
          schema:
            type: string
        - description: The search radius in meters.
          in: query
          name: radius
          schema:
            default: 1000
            format: int32
            type: integer
        - description: Maximum number of results to return.
          in: query
          name: limit
          schema:
            default: 10
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ATM"
                type: array
          description: A list of ATMs near the given address.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error
      summary: Retrieve a list of ATMs near a given address
      tags:
        - atms
  /atms/search:
    get:
      description: Search for ATMs based on geographical coordinates and radius.
      operationId: searchAtms
      parameters:
        - description: Latitude of the search location.
          in: query
          name: latitude
          required: true
          schema:
            format: double
            type: number
        - description: Longitude of the search location.
          in: query
          name: longitude
          required: true
          schema:
            format: double
            type: number
        - description: Search radius in meters.
          in: query
          name: radius
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ATM"
                type: array
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error
      summary: Search for ATMs based on geographical coordinates and radius
      tags:
        - atms
components:
  schemas:
    ATM:
      description: Represents an ATM object with its details.
      properties:
        accessHours:
          description: Operating hours of the ATM.
          type: string
        address:
          description: Physical address of the ATM.
          properties:
            city:
              description: City.
              type: string
            country:
              description: Country.
              type: string
            state:
              description: State.
              type: string
            street:
              description: Street address.
              type: string
            zipCode:
              description: Zip code.
              type: string
          required:
            - street
            - city
            - state
            - zipCode
            - country
          type: object
        atmId:
          description: Unique identifier for the ATM.
          type: string
        availability:
          description: Indicates whether the ATM is currently available.
          type: boolean
        features:
          description: List of supported features.
          items:
            description: >-
              Supported feature (e.g., cash withdrawal, deposit, balance
              inquiry).
            type: string
          type: array
        location:
          description: Geographical coordinates of the ATM.
          properties:
            latitude:
              description: Latitude of the location.
              format: double
              type: number
            longitude:
              description: Longitude of the location.
              format: double
              type: number
          required:
            - latitude
            - longitude
          type: object
        operator:
          description: Name of the ATM operator.
          type: string
      required:
        - atmId
        - operator
        - address
        - location
        - accessHours
        - availability
        - features
      type: object
    Address:
      description: Physical address of the ATM.
      properties:
        city:
          description: City.
          type: string
        country:
          description: Country.
          type: string
        state:
          description: State.
          type: string
        street:
          description: Street address.
          type: string
        zipCode:
          description: Zip code.
          type: string
      required:
        - street
        - city
        - state
        - zipCode
        - country
      type: object
    Error:
      description: Schema for error responses.
      properties:
        code:
          description: Error code indicating the type of error.
          type: string
        details:
          description: Optional details about the error.
          type: string
        message:
          description: Human-readable error message providing details about the error.
          type: string
      required:
        - code
        - message
      type: object
    Location:
      description: Geographical coordinates (latitude and longitude) of the ATM.
      properties:
        latitude:
          description: Latitude of the location.
          format: double
          type: number
        longitude:
          description: Longitude of the location.
          format: double
          type: number
      required:
        - latitude
        - longitude
      type: object
    Report:
      description: Details of a reported issue for an ATM.
      properties:
        atmId:
          description: ID of the ATM the report is about.
          type: string
        description:
          description: Description of the issue reported.
          type: string
        reportDate:
          description: Date and time the report was submitted.
          format: date-time
          type: string
        reportId:
          description: Unique identifier for the report.
          type: string
        reporter:
          description: Information about the reporter (e.g., user ID).
          type: string
        status:
          description: Status of the report (e.g., open, in progress, resolved).
          enum:
            - open
            - in progress
            - resolved
          type: string
      required:
        - reportId
        - atmId
        - reporter
        - description
        - reportDate
        - status
      type: object
